// The 50 U.S. states + Washington, D.C.
// Each plate has a color scheme loosely inspired by that state's real plate,
// plus a short nickname shown as the plate's subtitle. Rendered as CSS "plates"
// so the app stays self-contained (no external images, works offline).
//
// colors: { bg (plate face), text (main lettering), band (top/bottom accent), bandText }
const PLATES = [
  { code: "AL", name: "Alabama",       nick: "Sweet Home",        colors: { bg: "#f4f1e8", text: "#8a1a1a", band: "#8a1a1a", bandText: "#f4f1e8" } },
  { code: "AK", name: "Alaska",        nick: "The Last Frontier", colors: { bg: "#f8d94a", text: "#1c3f66", band: "#1c3f66", bandText: "#f8d94a" } },
  { code: "AZ", name: "Arizona",       nick: "Grand Canyon",      colors: { bg: "#e9d9b8", text: "#7a1f2b", band: "#4a6b3a", bandText: "#f4f1e8" } },
  { code: "AR", name: "Arkansas",      nick: "The Natural State", colors: { bg: "#eef2f4", text: "#b02a2a", band: "#2f6b4f", bandText: "#ffffff" } },
  { code: "CA", name: "California",    nick: "The Golden State",  colors: { bg: "#ffffff", text: "#003c6e", band: "#d43b00", bandText: "#ffffff" } },
  { code: "CO", name: "Colorado",      nick: "Colorful",          colors: { bg: "#2e6b3e", text: "#ffffff", band: "#12331f", bandText: "#9fd8a8" } },
  { code: "CT", name: "Connecticut",   nick: "Constitution",      colors: { bg: "#eef2f5", text: "#1c4e80", band: "#1c4e80", bandText: "#ffffff" } },
  { code: "DE", name: "Delaware",      nick: "The First State",   colors: { bg: "#0d2c54", text: "#f2c14e", band: "#f2c14e", bandText: "#0d2c54" } },
  { code: "DC", name: "District of Columbia", nick: "Taxation Without Representation", colors: { bg: "#ffffff", text: "#c8102e", band: "#0a2240", bandText: "#ffffff" } },
  { code: "FL", name: "Florida",       nick: "Sunshine State",    colors: { bg: "#ffffff", text: "#2e7d32", band: "#e08a1e", bandText: "#ffffff" } },
  { code: "GA", name: "Georgia",       nick: "Peach State",       colors: { bg: "#fdf1ea", text: "#3a5a40", band: "#e08a3e", bandText: "#ffffff" } },
  { code: "HI", name: "Hawaii",        nick: "Aloha State",       colors: { bg: "#e6f3f7", text: "#00695c", band: "#e08a3e", bandText: "#ffffff" } },
  { code: "ID", name: "Idaho",         nick: "Famous Potatoes",   colors: { bg: "#f4f1e8", text: "#1f5c3d", band: "#a01f2b", bandText: "#ffffff" } },
  { code: "IL", name: "Illinois",      nick: "Land of Lincoln",   colors: { bg: "#eef2f5", text: "#b31b1b", band: "#1c4e80", bandText: "#ffffff" } },
  { code: "IN", name: "Indiana",       nick: "The Hoosier State", colors: { bg: "#ffffff", text: "#12447a", band: "#c8102e", bandText: "#ffffff" } },
  { code: "IA", name: "Iowa",          nick: "The Hawkeye State", colors: { bg: "#eaf2ea", text: "#2f6b4f", band: "#1c4e80", bandText: "#ffffff" } },
  { code: "KS", name: "Kansas",        nick: "The Sunflower",     colors: { bg: "#0a2240", text: "#f2c14e", band: "#f2c14e", bandText: "#0a2240" } },
  { code: "KY", name: "Kentucky",      nick: "Bluegrass State",   colors: { bg: "#eef2f8", text: "#1c4e80", band: "#3a5a9a", bandText: "#ffffff" } },
  { code: "LA", name: "Louisiana",     nick: "Sportsman's Paradise", colors: { bg: "#f4f1e8", text: "#3a2c66", band: "#6b4ea0", bandText: "#ffffff" } },
  { code: "ME", name: "Maine",         nick: "Vacationland",      colors: { bg: "#fbfaf5", text: "#2f6b4f", band: "#c05a2e", bandText: "#ffffff" } },
  { code: "MD", name: "Maryland",      nick: "The Old Line State",colors: { bg: "#ffffff", text: "#b31b1b", band: "#e0a11e", bandText: "#000000" } },
  { code: "MA", name: "Massachusetts", nick: "The Bay State",     colors: { bg: "#ffffff", text: "#b31b1b", band: "#1c4e80", bandText: "#ffffff" } },
  { code: "MI", name: "Michigan",      nick: "Great Lakes",       colors: { bg: "#ffffff", text: "#1c4e80", band: "#0a2240", bandText: "#ffffff" } },
  { code: "MN", name: "Minnesota",     nick: "10,000 Lakes",      colors: { bg: "#eaf2ea", text: "#2f6b4f", band: "#1f5c3d", bandText: "#ffffff" } },
  { code: "MS", name: "Mississippi",   nick: "The Magnolia State",colors: { bg: "#f4f1e8", text: "#7a1f2b", band: "#2f6b4f", bandText: "#ffffff" } },
  { code: "MO", name: "Missouri",      nick: "The Show-Me State", colors: { bg: "#eef2f5", text: "#b31b1b", band: "#1c4e80", bandText: "#ffffff" } },
  { code: "MT", name: "Montana",       nick: "Big Sky Country",   colors: { bg: "#1f5c3d", text: "#f2c14e", band: "#12331f", bandText: "#f2c14e" } },
  { code: "NE", name: "Nebraska",      nick: "The Cornhusker",    colors: { bg: "#ffffff", text: "#1c4e80", band: "#c8102e", bandText: "#ffffff" } },
  { code: "NV", name: "Nevada",        nick: "The Silver State",  colors: { bg: "#eef2f5", text: "#3a5a9a", band: "#6b6b6b", bandText: "#ffffff" } },
  { code: "NH", name: "New Hampshire", nick: "Live Free or Die",  colors: { bg: "#f4f1e8", text: "#1f5c3d", band: "#2f6b4f", bandText: "#ffffff" } },
  { code: "NJ", name: "New Jersey",    nick: "The Garden State",  colors: { bg: "#f8e6b0", text: "#1c4e80", band: "#d4a017", bandText: "#0a2240" } },
  { code: "NM", name: "New Mexico",    nick: "Land of Enchantment", colors: { bg: "#f8d94a", text: "#a01f2b", band: "#a01f2b", bandText: "#f8d94a" } },
  { code: "NY", name: "New York",      nick: "The Empire State",  colors: { bg: "#f4c542", text: "#1c3a66", band: "#1c3a66", bandText: "#f4c542" } },
  { code: "NC", name: "North Carolina",nick: "First in Flight",   colors: { bg: "#ffffff", text: "#b31b1b", band: "#1c4e80", bandText: "#ffffff" } },
  { code: "ND", name: "North Dakota",  nick: "Peace Garden State",colors: { bg: "#dfeaf2", text: "#1c4e80", band: "#e08a3e", bandText: "#ffffff" } },
  { code: "OH", name: "Ohio",          nick: "The Buckeye State", colors: { bg: "#ffffff", text: "#b31b1b", band: "#1c4e80", bandText: "#ffffff" } },
  { code: "OK", name: "Oklahoma",      nick: "Native America",    colors: { bg: "#eaf2f4", text: "#00695c", band: "#c05a2e", bandText: "#ffffff" } },
  { code: "OR", name: "Oregon",        nick: "The Beaver State",  colors: { bg: "#dfeef0", text: "#1f5c3d", band: "#2f6b4f", bandText: "#ffffff" } },
  { code: "PA", name: "Pennsylvania",  nick: "The Keystone State",colors: { bg: "#f4f1e8", text: "#1c4e80", band: "#e0a11e", bandText: "#0a2240" } },
  { code: "RI", name: "Rhode Island",  nick: "The Ocean State",   colors: { bg: "#ffffff", text: "#1c6ea4", band: "#f2c14e", bandText: "#0a2240" } },
  { code: "SC", name: "South Carolina",nick: "The Palmetto State",colors: { bg: "#e6f3f7", text: "#1c4e80", band: "#3a5a9a", bandText: "#ffffff" } },
  { code: "SD", name: "South Dakota",  nick: "Mount Rushmore",    colors: { bg: "#eef2f5", text: "#7a1f2b", band: "#1c4e80", bandText: "#ffffff" } },
  { code: "TN", name: "Tennessee",     nick: "The Volunteer State", colors: { bg: "#eaf2ea", text: "#1f5c3d", band: "#e08a3e", bandText: "#ffffff" } },
  { code: "TX", name: "Texas",         nick: "The Lone Star State", colors: { bg: "#ffffff", text: "#1c3a66", band: "#b31b1b", bandText: "#ffffff" } },
  { code: "UT", name: "Utah",          nick: "Life Elevated",     colors: { bg: "#e9d9b8", text: "#a0451f", band: "#c05a2e", bandText: "#ffffff" } },
  { code: "VT", name: "Vermont",       nick: "The Green Mountain", colors: { bg: "#2e6b3e", text: "#ffffff", band: "#12331f", bandText: "#9fd8a8" } },
  { code: "VA", name: "Virginia",      nick: "Virginia is for Lovers", colors: { bg: "#ffffff", text: "#1c4e80", band: "#1f5c3d", bandText: "#ffffff" } },
  { code: "WA", name: "Washington",    nick: "The Evergreen State", colors: { bg: "#ffffff", text: "#1f5c3d", band: "#2f6b4f", bandText: "#ffffff" } },
  { code: "WV", name: "West Virginia", nick: "Wild and Wonderful", colors: { bg: "#eef2f5", text: "#1c4e80", band: "#e0a11e", bandText: "#0a2240" } },
  { code: "WI", name: "Wisconsin",     nick: "America's Dairyland", colors: { bg: "#f4f1e8", text: "#a01f2b", band: "#1f5c3d", bandText: "#ffffff" } },
  { code: "WY", name: "Wyoming",       nick: "Forever West",      colors: { bg: "#f8d94a", text: "#7a1f2b", band: "#7a1f2b", bandText: "#f8d94a" } },
];

if (typeof module !== "undefined") { module.exports = PLATES; }
